"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Olive.py']
DATA_FILES = ['olivedesk.icns', 'olivemenu.icns', 'olivemenu.png', 'wechat50.png', 'wechat20.png', 
              'wechat10.png', 'wechat5.png', 'alipay50.png', 'alipay20.png', 
              'alipay10.png', 'alipay5.png', 'multinum.txt', 'tarlist.txt', 'showlist.txt', 'back4.png']
OPTIONS = {'iconfile': 'olivedesk.icns',
           'packages': ['PyQt6', 'applescript', 'subprocess', 'codecs', 'AppKit'],
           'plist': {
            'CFBundleShortVersionString': '0.1.9',
            'LSUIElement': True,
            },
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    author='Ryan-the-hito',
    version='0.1.9'
)
